db:
  environment:
    MYSQL_ROOT_PASSWORD: root
  image: centurylink/mysql
  ports:
    - 3306
  volumes:
    - .data:/var/lib/mysql

web:
  build: docker/development_image
  command: bundle exec rails s --pid=/tmp/server.pid
  environment:
    VIRTUAL_HOST: web.probebe.dev
    ZENVIA_ACCOUNT: zeroaseis.connectweb
    ZENVIA_PASSWORD: 206Opr3Cu6
  links:
    - db
    - mail
    - rpush
    - redis
  ports:
    - 3000
  volumes:
    - .:/app
    - ../carnival:/carnival
  working_dir: /app

mail:
  image: schickling/mailcatcher
  environment:
    VIRTUAL_HOST: mail.probebe.dev
    VIRTUAL_PORT: 1080

rpush:
  build: docker/development_image
  command: bundle exec rpush start --foreground --pid-file=/tmp/rpush.pid
  links:
    - db
  volumes:
    - .:/app
  working_dir: /app

redis:
  image: redis
  ports:
    - 6379

sidekiq:
  build: docker/development_image
  command: bundle exec sidekiq --pidfile=/tmp/sidekiq.pid
  links:
    - redis
    - db
  volumes:
    - .:/app
  working_dir: /app
