db:
  environment:
    MYSQL_ROOT_PASSWORD: root
  image: centurylink/mysql
  ports:
    - 3306
  volumes:
    - .data:/var/lib/mysql

web:
  build: docker/development_image
  command: bundle exec rails s --pid=/tmp/server.pid
  environment:
    VIRTUAL_HOST: web.probebe.dev
    ZENVIA_ACCOUNT: zeroaseis.connectweb
    ZENVIA_PASSWORD: 206Opr3Cu6
    TELEIN_KEY: 19cbe523ebe3ee759d67
    AWS_REGION: us-east-1
  links:
    - db
    - mail
    - redis
    - elasticsearch
  ports:
    - 3000:3000
  volumes:
    - .:/app
  working_dir: /app

mail:
  image: schickling/mailcatcher
  environment:
    VIRTUAL_HOST: mail.probebe.dev
    VIRTUAL_PORT: 1080

redis:
  image: redis
  ports:
    - 6379

sidekiq:
  build: docker/development_image
  command: bundle exec sidekiq --pidfile=/tmp/sidekiq.pid
  links:
    - redis
    - db
  volumes:
    - .:/app
  working_dir: /app

elasticsearch:
  image: elasticsearch:1.5
  environment:
    VIRTUAL_HOST: elasticsearch.dev
  ports:
    - "9200:9200"
    - "9300:9300"
