default: &default
  adapter: mysql2
  pool: 10
  timeout: 5000
  username: root
  password: root
  #host: db

development:
  <<: *default
  database: probebe_development

test:
  pool: 1
  adapter: sqlite3
  database: ":memory:"

staging:
  <<: *default
  database: '<%= ENV['RDS_DB_NAME'] %>'
  username: '<%= ENV['RDS_USERNAME'] %>'
  password: '<%= ENV['RDS_PASSWORD'] %>'
  host: '<%= ENV['RDS_HOSTNAME'] %>'
  port: '<%= ENV['RDS_PORT'] %>'

production:
  <<: *default
  database: '<%= ENV['RDS_DB_NAME'] %>'
  username: '<%= ENV['RDS_USERNAME'] %>'
  password: '<%= ENV['RDS_PASSWORD'] %>'
  host: '<%= ENV['RDS_HOSTNAME'] %>'
  port: '<%= ENV['RDS_PORT'] %>'
