alias rspec="bundle exec spring rspec"
alias dbmigrate="bundle exec spring rake db:migrate"
alias dbreset="bundle exec spring rake db:migrate:reset"
alias dbseed="bundle exec spring rake db:seed"
alias railsc="bundle exec spring rails c"
alias railss="bundle exec spring rails s"
alias railsr="bundle exec spring rails r"
alias spring="bundle exec spring"
