---
- hosts: all
  sudo: yes
  roles:
    - { role: lxhunter.apt, apt_install_packages: ['git', 'libmysqld-dev', 'curl'] }
    - { role: rvm_io.rvm1-ruby, rvm1_rubies: ['2.1.3'] }
    - { role: ANXS.mysql, mysql_root_passwor: root }
    - { role: JasonGiedymin.nodejs, nodejs_version: '0.10.32' }
