---
- hosts: all
  sudo: yes
  roles:
    - { role: lxhunter.apt, apt_install_packages: ['git', 'libmysqld-dev', 'curl', 'nodejs', 'npm', 'qt5-default', 'libqt5webkit5-dev', 'xvfb'] }
    - { role: ANXS.mysql, mysql_root_password: root, mysql_users: [ { name: 'admin', pass: 'root', priv: '*.*:ALL', host: '%' } ] }
    - { role: franklinkim.hosts, hosts: [{ip: '127.0.0.1', domain: 'db_1'}] }
